# Generated by Django 2.2.3 on 2019-07-17 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneylog',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
