# Generated by Django 2.2.3 on 2019-07-17 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_task_money'),
        ('billing', '0003_auto_20190717_0334'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneylog',
            name='task',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='task.Task'),
        ),
    ]
