# Generated by Django 2.2.3 on 2019-07-13 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'CUSTOMER'), (2, 'EXECUTOR')], default=2),
        ),
    ]
